const yc_persistence_service = "function yc_persistence_service(jwt, tenantID, body, callback) {\n"
+ "  let endpoint = 'http://api.ycodify.com/baas/interpreter-p/s';\n"
+ "  let request = new XMLHttpRequest();\n"
+ "  request.open(\"POST\", endpoint, true);\n"
+ "  request.setRequestHeader('Authorization', 'Bearer '.concat(jwt));\n"
+ "  request.setRequestHeader('X-TenantID', tenantID);\n"
+ "  request.setRequestHeader('Content-type', 'application/json');\n"
+ "  request.setRequestHeader('Accept', 'application/json');\n"
+ "  request.onreadystatechange = function() {\n"
+ "    if (this.readyState == 4\n"
+ "      && (this.status == 200 || this.status == 201)) {\n"
+ "      callback(this.responseText);\n"
+ "    } else alert(this.response);\n"
+ "  };\n"
+ "  request.send(body);\n"
+ "}";